export const els = {
  status: document.querySelector("#apiStatus"),
  title: document.querySelector("#screenTitle"),
  context: document.querySelector("#contextLabel"),
  athleteList: document.querySelector("#athleteList"),
  athleteSearch: document.querySelector("#athleteSearch"),
  athletesToggle: document.querySelector("#athletesToggle"),
  railToggle: document.querySelector("#railToggle"),
  calendarToggle: document.querySelector("#calendarToggle"),
  tabs: document.querySelectorAll(".tab"),
  libraryTabs: document.querySelectorAll("[data-library-tab]"),
  athleteTabs: document.querySelectorAll("[data-athlete-tab]"),
  toolbar: document.querySelector("#viewToolbar"),
  content: document.querySelector("#content"),
  mediaModal: document.querySelector("#mediaModal"),
  mediaTitle: document.querySelector("#mediaTitle"),
  mediaBody: document.querySelector("#mediaBody"),
  signOut: document.querySelector("#signOutButton"),
  notificationToggle: document.querySelector("#notificationToggle"),
  notificationPanel: document.querySelector("#notificationPanel"),
  messageToggle: document.querySelector("#messageToggle"),
  messagePanel: document.querySelector("#messagePanel"),
  userRole: document.querySelector("#userRole"),
};
